[2024-02-20T11:03:35.801+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.Extract_data manual__2024-02-20T11:03:29.528324+00:00 [queued]>
[2024-02-20T11:03:35.811+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.Extract_data manual__2024-02-20T11:03:29.528324+00:00 [queued]>
[2024-02-20T11:03:35.812+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-20T11:03:35.828+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Extract_data> on 2024-02-20 11:03:29.528324+00:00
[2024-02-20T11:03:35.841+0000] {standard_task_runner.py:60} INFO - Started process 5825 to run task
[2024-02-20T11:03:35.844+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'Extract_data', 'manual__2024-02-20T11:03:29.528324+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmprhj_7yyk']
[2024-02-20T11:03:35.847+0000] {standard_task_runner.py:88} INFO - Job 71: Subtask Extract_data
[2024-02-20T11:03:35.866+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-20T11:03:35.909+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.Extract_data manual__2024-02-20T11:03:29.528324+00:00 [running]> on host 0980836b8fdf
[2024-02-20T11:03:36.001+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='Extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-20T11:03:29.528324+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-20T11:03:29.528324+00:00'
[2024-02-20T11:03:36.004+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
TypeError: __init__() missing 1 required positional argument: 'task_id'
[2024-02-20T11:03:36.015+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=***-s3-mlflow, task_id=Extract_data, execution_date=20240220T110329, start_date=20240220T110335, end_date=20240220T110336
[2024-02-20T11:03:36.027+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 71 for task Extract_data (__init__() missing 1 required positional argument: 'task_id'; 5825)
[2024-02-20T11:03:36.057+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-20T11:03:36.089+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
