[2024-02-20T13:30:04.596+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.model_training manual__2024-02-20T13:29:41.348867+00:00 [queued]>
[2024-02-20T13:30:04.605+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.model_training manual__2024-02-20T13:29:41.348867+00:00 [queued]>
[2024-02-20T13:30:04.606+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-20T13:30:04.622+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): model_training> on 2024-02-20 13:29:41.348867+00:00
[2024-02-20T13:30:04.631+0000] {standard_task_runner.py:60} INFO - Started process 2553 to run task
[2024-02-20T13:30:04.635+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'model_training', 'manual__2024-02-20T13:29:41.348867+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmpgmy8jwq5']
[2024-02-20T13:30:04.637+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask model_training
[2024-02-20T13:30:04.654+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-20T13:30:04.689+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.model_training manual__2024-02-20T13:29:41.348867+00:00 [running]> on host eb0fadca60cf
[2024-02-20T13:30:04.763+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='model_training' AIRFLOW_CTX_EXECUTION_DATE='2024-02-20T13:29:41.348867+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-20T13:29:41.348867+00:00'
[2024-02-20T13:30:04.962+0000] {logging_mixin.py:188} INFO - data imported from s3
[2024-02-20T13:30:05.023+0000] {logging_mixin.py:188} INFO - [5.85282782 6.09774808 5.97958012 ... 6.14141638 5.96909794 5.96807435]
[2024-02-20T13:30:05.029+0000] {logging_mixin.py:188} INFO -  RMSE: 0.8539085948361889
[2024-02-20T13:30:05.031+0000] {logging_mixin.py:188} INFO -  MAE:  0.6443287167474065
[2024-02-20T13:30:05.033+0000] {logging_mixin.py:188} INFO -  R2:  0.04227624654013584
[2024-02-20T13:30:05.037+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-20T13:30:05.065+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=model_training, execution_date=20240220T132941, start_date=20240220T133004, end_date=20240220T133005
[2024-02-20T13:30:05.171+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-20T13:30:05.193+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
