[2024-02-21T10:15:18.992+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-21T10:15:00.704998+00:00 [queued]>
[2024-02-21T10:15:19.002+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-21T10:15:00.704998+00:00 [queued]>
[2024-02-21T10:15:19.003+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T10:15:19.018+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-02-21 10:15:00.704998+00:00
[2024-02-21T10:15:19.027+0000] {standard_task_runner.py:60} INFO - Started process 936 to run task
[2024-02-21T10:15:19.030+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'upload_to_s3', 'manual__2024-02-21T10:15:00.704998+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmpc0vo8w0y']
[2024-02-21T10:15:19.033+0000] {standard_task_runner.py:88} INFO - Job 52: Subtask upload_to_s3
[2024-02-21T10:15:19.052+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-21T10:15:19.093+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-21T10:15:00.704998+00:00 [running]> on host b14d6cdb7c29
[2024-02-21T10:15:19.180+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-21T10:15:00.704998+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-21T10:15:00.704998+00:00'
[2024-02-21T10:15:19.521+0000] {base_aws.py:581} WARNING - Unable to find AWS Connection ID 's3_conn', switching to empty.
[2024-02-21T10:15:19.522+0000] {base_aws.py:161} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2024-02-21T10:15:19.891+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-02-21T10:15:21.803+0000] {logging_mixin.py:188} INFO - datafile uploaded successfully
[2024-02-21T10:15:21.807+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T10:15:21.818+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=upload_to_s3, execution_date=20240221T101500, start_date=20240221T101518, end_date=20240221T101521
[2024-02-21T10:15:21.862+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T10:15:21.895+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
