[2024-02-20T07:34:45.473+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:34:45.478+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:34:45.492+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:34:45.485+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:34:50.087+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:34:50.079+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 38, in <module>
    python_callable= hello3)
NameError: name 'hello3' is not defined
[2024-02-20T07:34:50.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:34:50.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 4.685 seconds
[2024-02-20T07:35:00.272+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:00.274+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:35:00.275+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:35:00.275+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:00.740+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:35:00.719+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 38, in <module>
    python_callable= extract)
NameError: name 'hello3' is not defined
[2024-02-20T07:35:00.743+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:00.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.508 seconds
[2024-02-20T07:35:10.659+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:10.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:35:10.662+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:35:10.662+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:11.112+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:35:11.106+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:35:11.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:11.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.489 seconds
[2024-02-20T07:35:21.279+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:21.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:35:21.283+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:35:21.282+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:21.706+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:35:21.701+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:35:21.709+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:21.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.454 seconds
[2024-02-20T07:35:31.882+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:31.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:35:31.885+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:35:31.884+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:32.337+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:35:32.329+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:35:32.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:32.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.483 seconds
[2024-02-20T07:35:42.496+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:42.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:35:42.499+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:35:42.498+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:42.974+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:35:42.970+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:35:42.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:42.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.506 seconds
[2024-02-20T07:35:53.166+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:53.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:35:53.169+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:35:53.169+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:53.665+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:35:53.660+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:35:53.667+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:35:53.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.531 seconds
[2024-02-20T07:36:03.843+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:03.845+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:36:03.846+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:36:03.846+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:04.242+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:36:04.235+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:36:04.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:04.266+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.426 seconds
[2024-02-20T07:36:14.440+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:14.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:36:14.443+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:36:14.443+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:14.836+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:36:14.828+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:36:14.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:14.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.437 seconds
[2024-02-20T07:36:25.020+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:25.022+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:36:25.023+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:36:25.023+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:25.391+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:36:25.383+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:36:25.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:25.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.399 seconds
[2024-02-20T07:36:35.556+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:35.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:36:35.559+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:36:35.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:35.986+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:36:35.980+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:36:35.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:36.011+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.458 seconds
[2024-02-20T07:36:46.165+0000] {processor.py:161} INFO - Started process (PID=235) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:46.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:36:46.169+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:36:46.169+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:46.637+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:36:46.631+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:36:46.640+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:46.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.501 seconds
[2024-02-20T07:36:56.780+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:56.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:36:56.783+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:36:56.783+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:57.172+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:36:57.167+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:36:57.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:36:57.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.428 seconds
[2024-02-20T07:37:07.356+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:07.358+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:37:07.359+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:37:07.359+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:07.766+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:37:07.758+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:37:07.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:07.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.437 seconds
[2024-02-20T07:37:17.939+0000] {processor.py:161} INFO - Started process (PID=253) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:17.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:37:17.942+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:37:17.941+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:18.362+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:37:18.355+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:37:18.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:18.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.447 seconds
[2024-02-20T07:37:28.532+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:28.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:37:28.535+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:37:28.535+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:28.981+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:37:28.974+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:37:28.985+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:29.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.488 seconds
[2024-02-20T07:37:39.155+0000] {processor.py:161} INFO - Started process (PID=265) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:39.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:37:39.157+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:37:39.157+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:39.525+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:37:39.521+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:37:39.526+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:39.547+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.396 seconds
[2024-02-20T07:37:49.699+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:49.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:37:49.702+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:37:49.702+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:50.171+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:37:50.165+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:37:50.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:37:50.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.525 seconds
[2024-02-20T07:38:00.380+0000] {processor.py:161} INFO - Started process (PID=277) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:00.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:38:00.383+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:38:00.383+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:00.782+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:38:00.777+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:38:00.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:00.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.428 seconds
[2024-02-20T07:38:10.956+0000] {processor.py:161} INFO - Started process (PID=283) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:10.957+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:38:10.959+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:38:10.958+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:11.349+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:38:11.342+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:38:11.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:11.374+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.422 seconds
[2024-02-20T07:38:21.522+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:21.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:38:21.525+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:38:21.524+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:21.974+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:38:21.967+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:38:21.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:22.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.491 seconds
[2024-02-20T07:38:32.124+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:32.126+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:38:32.127+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:38:32.127+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:32.565+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:38:32.557+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:38:32.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:32.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.469 seconds
[2024-02-20T07:38:42.725+0000] {processor.py:161} INFO - Started process (PID=301) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:42.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:38:42.727+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:38:42.727+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:43.154+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:38:43.147+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:38:43.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:43.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.459 seconds
[2024-02-20T07:38:53.323+0000] {processor.py:161} INFO - Started process (PID=307) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:53.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:38:53.326+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:38:53.326+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:53.716+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:38:53.708+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:38:53.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:38:53.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.417 seconds
[2024-02-20T07:39:03.903+0000] {processor.py:161} INFO - Started process (PID=313) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:03.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:39:03.905+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:39:03.905+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:04.296+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:39:04.286+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:39:04.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:04.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.431 seconds
[2024-02-20T07:39:14.471+0000] {processor.py:161} INFO - Started process (PID=319) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:14.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:39:14.474+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:39:14.474+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:14.864+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:39:14.858+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:39:14.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:14.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.421 seconds
[2024-02-20T07:39:25.034+0000] {processor.py:161} INFO - Started process (PID=325) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:25.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:39:25.037+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:39:25.036+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:25.497+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:39:25.490+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:39:25.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:25.521+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.490 seconds
[2024-02-20T07:39:35.649+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:35.650+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:39:35.652+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:39:35.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:36.064+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:39:36.060+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:39:36.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:36.082+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.436 seconds
[2024-02-20T07:39:46.273+0000] {processor.py:161} INFO - Started process (PID=337) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:46.275+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:39:46.276+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:39:46.276+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:46.685+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:39:46.680+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:39:46.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:46.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.464 seconds
[2024-02-20T07:39:56.897+0000] {processor.py:161} INFO - Started process (PID=343) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:56.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:39:56.900+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:39:56.900+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:57.283+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:39:57.276+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:39:57.286+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:39:57.315+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.422 seconds
[2024-02-20T07:40:07.445+0000] {processor.py:161} INFO - Started process (PID=349) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:07.447+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:40:07.448+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:07.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:07.872+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:07.868+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:40:07.875+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:07.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.465 seconds
[2024-02-20T07:40:18.042+0000] {processor.py:161} INFO - Started process (PID=355) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:18.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:40:18.045+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:18.044+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:18.422+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:18.415+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= hello)
NameError: name 'hello' is not defined
[2024-02-20T07:40:18.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:18.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.406 seconds
[2024-02-20T07:40:22.091+0000] {processor.py:161} INFO - Started process (PID=361) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:22.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:40:22.094+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:22.094+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:22.543+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:22.537+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 34, in <module>
    python_callable= start)
NameError: name 'start' is not defined
[2024-02-20T07:40:22.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:22.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.474 seconds
[2024-02-20T07:40:29.623+0000] {processor.py:161} INFO - Started process (PID=367) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:29.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:40:29.627+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:29.627+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:29.653+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:29.652+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 15
    from
        ^
SyntaxError: invalid syntax
[2024-02-20T07:40:29.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:29.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.057 seconds
[2024-02-20T07:40:32.707+0000] {processor.py:161} INFO - Started process (PID=372) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:32.708+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:40:32.710+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:32.709+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:32.740+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:32.739+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 15
    from src.
            ^
SyntaxError: invalid syntax
[2024-02-20T07:40:32.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:32.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.064 seconds
[2024-02-20T07:40:34.774+0000] {processor.py:161} INFO - Started process (PID=377) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:34.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:40:34.778+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:34.778+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:34.806+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:34.805+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 15
    from src.dummy
                 ^
SyntaxError: invalid syntax
[2024-02-20T07:40:34.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:34.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.059 seconds
[2024-02-20T07:40:36.878+0000] {processor.py:161} INFO - Started process (PID=382) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:36.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:40:36.881+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:36.881+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:36.917+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:36.917+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 15
    from src.dummy.
                  ^
SyntaxError: invalid syntax
[2024-02-20T07:40:36.919+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:36.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.075 seconds
[2024-02-20T07:40:38.923+0000] {processor.py:161} INFO - Started process (PID=387) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:38.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:40:38.926+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:38.926+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:38.950+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:38.949+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 15
    from src.dummy.s
                   ^
SyntaxError: invalid syntax
[2024-02-20T07:40:38.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:38.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.054 seconds
[2024-02-20T07:40:46.006+0000] {processor.py:161} INFO - Started process (PID=392) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:46.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:40:46.009+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:46.009+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:46.459+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:46.453+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 15, in <module>
    from src.dummy.start import star
ImportError: cannot import name 'star' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:40:46.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:46.480+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.477 seconds
[2024-02-20T07:40:47.091+0000] {processor.py:161} INFO - Started process (PID=398) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:47.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:40:47.094+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:47.094+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:47.581+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:47.578+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 40, in <module>
    python_callable= extract)
NameError: name 'extract' is not defined
[2024-02-20T07:40:47.583+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:47.606+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.519 seconds
[2024-02-20T07:40:57.730+0000] {processor.py:161} INFO - Started process (PID=404) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:57.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:40:57.732+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:57.732+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:58.185+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:58.180+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 40, in <module>
    python_callable= extract)
NameError: name 'extract' is not defined
[2024-02-20T07:40:58.187+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:58.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.483 seconds
[2024-02-20T07:40:59.779+0000] {processor.py:161} INFO - Started process (PID=410) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:40:59.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:40:59.781+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:40:59.781+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:00.294+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:00.291+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 40, in <module>
    python_callable= extract)
NameError: name 'extract' is not defined
[2024-02-20T07:41:00.295+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:00.309+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.534 seconds
[2024-02-20T07:41:04.328+0000] {processor.py:161} INFO - Started process (PID=416) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:04.330+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:41:04.331+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:04.331+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:04.810+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:04.806+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 40, in <module>
    python_callable= extract)
NameError: name 'extract' is not defined
[2024-02-20T07:41:04.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:04.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.518 seconds
[2024-02-20T07:41:11.449+0000] {processor.py:161} INFO - Started process (PID=422) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:11.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:41:11.451+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:11.451+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:11.882+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:11.878+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 40, in <module>
    python_callable= extract)
NameError: name 'extract' is not defined
[2024-02-20T07:41:11.884+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:11.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.477 seconds
[2024-02-20T07:41:12.970+0000] {processor.py:161} INFO - Started process (PID=428) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:12.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:41:12.973+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:12.973+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:13.403+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:13.396+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 40, in <module>
    python_callable= extract)
NameError: name 'extract' is not defined
[2024-02-20T07:41:13.405+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:13.439+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.472 seconds
[2024-02-20T07:41:20.063+0000] {processor.py:161} INFO - Started process (PID=434) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:20.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:41:20.065+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:20.065+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:20.530+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:20.526+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 40, in <module>
    python_callable= extract)
NameError: name 'extract' is not defined
[2024-02-20T07:41:20.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:20.553+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.494 seconds
[2024-02-20T07:41:21.585+0000] {processor.py:161} INFO - Started process (PID=440) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:21.586+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:41:21.588+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:21.587+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:22.012+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:22.006+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 40, in <module>
    python_callable= extract)
NameError: name 'extract' is not defined
[2024-02-20T07:41:22.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:22.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.452 seconds
[2024-02-20T07:41:25.678+0000] {processor.py:161} INFO - Started process (PID=446) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:25.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:41:25.681+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:25.681+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:26.162+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:26.157+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 40, in <module>
    python_callable= extract)
NameError: name 'extract' is not defined
[2024-02-20T07:41:26.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:26.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.518 seconds
[2024-02-20T07:41:30.289+0000] {processor.py:161} INFO - Started process (PID=452) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:30.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:41:30.291+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:30.291+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:30.726+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:30.719+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 40, in <module>
    python_callable= end)
NameError: name 'end' is not defined
[2024-02-20T07:41:30.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:30.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.482 seconds
[2024-02-20T07:41:40.924+0000] {processor.py:161} INFO - Started process (PID=458) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:40.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:41:40.927+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:40.927+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:41.437+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:41.434+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 40, in <module>
    python_callable= end)
NameError: name 'end' is not defined
[2024-02-20T07:41:41.439+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:41.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.538 seconds
[2024-02-20T07:41:42.419+0000] {processor.py:161} INFO - Started process (PID=464) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:42.421+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:41:42.422+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:42.422+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:42.900+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:42.892+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 41, in <module>
    python_callable= end)
NameError: name 'end' is not defined
[2024-02-20T07:41:42.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:42.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.517 seconds
[2024-02-20T07:41:46.006+0000] {processor.py:161} INFO - Started process (PID=470) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:46.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:41:46.009+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:46.008+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:46.491+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:46.485+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 16, in <module>
    from src.dummy.start import end
ImportError: cannot import name 'end' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:41:46.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:46.523+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.520 seconds
[2024-02-20T07:41:50.605+0000] {processor.py:161} INFO - Started process (PID=476) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:50.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:41:50.608+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:50.608+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:51.035+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:41:51.028+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 16, in <module>
    from src.dummy.start import end
ImportError: cannot import name 'end' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:41:51.037+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:41:51.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.460 seconds
[2024-02-20T07:42:01.203+0000] {processor.py:161} INFO - Started process (PID=482) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:01.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:42:01.206+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:01.206+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:01.653+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:01.647+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 16, in <module>
    from src.dummy.start import end
ImportError: cannot import name 'end' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:42:01.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:01.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.476 seconds
[2024-02-20T07:42:05.748+0000] {processor.py:161} INFO - Started process (PID=488) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:05.750+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:42:05.751+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:05.751+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:06.229+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:06.222+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 16, in <module>
    from src.dummy.start import end
ImportError: cannot import name 'end' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:42:06.231+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:06.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.519 seconds
[2024-02-20T07:42:11.377+0000] {processor.py:161} INFO - Started process (PID=494) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:11.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:42:11.381+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:11.380+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:11.852+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:11.847+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 16, in <module>
    from src.dummy.start import end
ImportError: cannot import name 'end' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:42:11.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:11.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.528 seconds
[2024-02-20T07:42:13.828+0000] {processor.py:161} INFO - Started process (PID=500) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:13.829+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:42:13.830+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:13.830+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:14.289+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:14.285+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 16, in <module>
    from src.dummy.start import end
ImportError: cannot import name 'end' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:42:14.291+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:14.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.485 seconds
[2024-02-20T07:42:15.001+0000] {processor.py:161} INFO - Started process (PID=506) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:15.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:42:15.004+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:15.004+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:15.034+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:15.033+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 48
    Start_process>>
                  ^
SyntaxError: invalid syntax
[2024-02-20T07:42:15.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:15.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.059 seconds
[2024-02-20T07:42:18.057+0000] {processor.py:161} INFO - Started process (PID=511) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:18.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:42:18.060+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:18.060+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:18.534+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:18.529+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 16, in <module>
    from src.dummy.start import end
ImportError: cannot import name 'end' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:42:18.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:18.554+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.500 seconds
[2024-02-20T07:42:19.179+0000] {processor.py:161} INFO - Started process (PID=517) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:19.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:42:19.181+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:19.181+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:19.618+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:19.609+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 16, in <module>
    from src.dummy.start import end
ImportError: cannot import name 'end' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:42:19.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:19.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.462 seconds
[2024-02-20T07:42:20.630+0000] {processor.py:161} INFO - Started process (PID=523) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:20.631+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:42:20.633+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:20.632+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:21.111+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:21.106+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 16, in <module>
    from src.dummy.start import end
ImportError: cannot import name 'end' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:42:21.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:21.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.514 seconds
[2024-02-20T07:42:27.776+0000] {processor.py:161} INFO - Started process (PID=529) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:27.777+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:42:27.778+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:27.778+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:28.218+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:28.213+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 16, in <module>
    from src.dummy.start import end
ImportError: cannot import name 'end' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:42:28.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:28.251+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.479 seconds
[2024-02-20T07:42:38.376+0000] {processor.py:161} INFO - Started process (PID=535) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:38.377+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:42:38.379+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:38.379+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:38.895+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:38.888+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 16, in <module>
    from src.dummy.start import end
ImportError: cannot import name 'end' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:42:38.898+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:38.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.542 seconds
[2024-02-20T07:42:49.072+0000] {processor.py:161} INFO - Started process (PID=541) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:49.074+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:42:49.075+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:49.075+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:49.476+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:49.473+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 16, in <module>
    from src.dummy.start import end
ImportError: cannot import name 'end' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:42:49.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:49.493+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.425 seconds
[2024-02-20T07:42:59.574+0000] {processor.py:161} INFO - Started process (PID=547) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:42:59.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:42:59.578+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:42:59.578+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:00.014+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:00.010+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 16, in <module>
    from src.dummy.start import end
ImportError: cannot import name 'end' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:43:00.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:00.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.462 seconds
[2024-02-20T07:43:10.178+0000] {processor.py:161} INFO - Started process (PID=553) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:10.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:43:10.181+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:10.181+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:10.588+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:10.585+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 16, in <module>
    from src.dummy.start import end
ImportError: cannot import name 'end' from 'src.dummy.start' (/opt/airflow/src/dummy/start.py)
[2024-02-20T07:43:10.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:10.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.430 seconds
[2024-02-20T07:43:14.231+0000] {processor.py:161} INFO - Started process (PID=559) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:14.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:43:14.233+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:14.233+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:14.727+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:14.718+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 43, in <module>
    end_process= PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 184, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'Start_Pipeline' has already been added to the DAG
[2024-02-20T07:43:14.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:14.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.521 seconds
[2024-02-20T07:43:24.910+0000] {processor.py:161} INFO - Started process (PID=565) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:24.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:43:24.913+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:24.913+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:25.436+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:25.424+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 43, in <module>
    end_process= PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 184, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'Start_Pipeline' has already been added to the DAG
[2024-02-20T07:43:25.436+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:25.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.559 seconds
[2024-02-20T07:43:35.624+0000] {processor.py:161} INFO - Started process (PID=571) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:35.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:43:35.628+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:35.627+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:36.125+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:36.115+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 43, in <module>
    end_process= PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 184, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'Start_Pipeline' has already been added to the DAG
[2024-02-20T07:43:36.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:36.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.528 seconds
[2024-02-20T07:43:46.291+0000] {processor.py:161} INFO - Started process (PID=577) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:46.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:43:46.294+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:46.294+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:46.774+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:46.769+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow-mlflow-s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-mlflow-s3.py", line 43, in <module>
    end_process= PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 184, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'Start_Pipeline' has already been added to the DAG
[2024-02-20T07:43:46.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:46.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.507 seconds
[2024-02-20T07:43:56.960+0000] {processor.py:161} INFO - Started process (PID=583) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:56.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:43:56.963+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:56.962+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:57.505+0000] {processor.py:840} INFO - DAG(s) 'airflow-s3-mlflow' retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:43:57.944+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:57.942+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:airflow-s3-mlflow
[2024-02-20T07:43:57.958+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:57.958+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:airflow-s3-mlflow
[2024-02-20T07:43:57.969+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:57.968+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:airflow-s3-mlflow
[2024-02-20T07:43:57.971+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:57.970+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-20T07:43:57.980+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:57.980+0000] {dag.py:3058} INFO - Creating ORM DAG for airflow-s3-mlflow
[2024-02-20T07:43:57.993+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:43:57.992+0000] {dag.py:3823} INFO - Setting next_dagrun for airflow-s3-mlflow to 2024-02-20 00:00:00+00:00, run_after=2024-02-21 00:00:00+00:00
[2024-02-20T07:43:58.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 1.066 seconds
[2024-02-20T07:44:08.179+0000] {processor.py:161} INFO - Started process (PID=589) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:44:08.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:44:08.182+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:44:08.181+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:44:08.651+0000] {processor.py:840} INFO - DAG(s) 'airflow-s3-mlflow' retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:44:08.662+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:44:08.662+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-20T07:44:08.680+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:44:08.680+0000] {dag.py:3823} INFO - Setting next_dagrun for airflow-s3-mlflow to 2024-02-20 00:00:00+00:00, run_after=2024-02-21 00:00:00+00:00
[2024-02-20T07:44:08.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.530 seconds
[2024-02-20T07:44:18.886+0000] {processor.py:161} INFO - Started process (PID=595) to work on /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:44:18.888+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-mlflow-s3.py for tasks to queue
[2024-02-20T07:44:18.889+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:44:18.889+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:44:19.337+0000] {processor.py:840} INFO - DAG(s) 'airflow-s3-mlflow' retrieved from /opt/airflow/dags/airflow-mlflow-s3.py
[2024-02-20T07:44:19.346+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:44:19.346+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-20T07:44:19.363+0000] {logging_mixin.py:188} INFO - [2024-02-20T07:44:19.363+0000] {dag.py:3823} INFO - Setting next_dagrun for airflow-s3-mlflow to 2024-02-20 00:00:00+00:00, run_after=2024-02-21 00:00:00+00:00
[2024-02-20T07:44:19.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-mlflow-s3.py took 0.502 seconds
