[2024-02-20T10:23:17.707+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-20T10:22:45.786359+00:00 [queued]>
[2024-02-20T10:23:17.721+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-20T10:22:45.786359+00:00 [queued]>
[2024-02-20T10:23:17.722+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-20T10:23:17.746+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-02-20 10:22:45.786359+00:00
[2024-02-20T10:23:17.764+0000] {standard_task_runner.py:60} INFO - Started process 3970 to run task
[2024-02-20T10:23:17.772+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'upload_to_s3', 'manual__2024-02-20T10:22:45.786359+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmpveylyoqj']
[2024-02-20T10:23:17.777+0000] {standard_task_runner.py:88} INFO - Job 40: Subtask upload_to_s3
[2024-02-20T10:23:17.813+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-20T10:23:17.863+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-20T10:22:45.786359+00:00 [running]> on host 0980836b8fdf
[2024-02-20T10:23:17.989+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-20T10:22:45.786359+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-20T10:22:45.786359+00:00'
[2024-02-20T10:23:18.275+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/src/preprocessing/uploaddata.py", line 14, in upload_to_s3
    s3_hook.load_string(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 122, in wrapper
    bound_args = function_signature.bind(*args, **kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3007, in _bind
    raise TypeError('missing a required argument: {arg!r}'. \
TypeError: missing a required argument: 'key'
[2024-02-20T10:23:18.313+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=***-s3-mlflow, task_id=upload_to_s3, execution_date=20240220T102245, start_date=20240220T102317, end_date=20240220T102318
[2024-02-20T10:23:18.335+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 40 for task upload_to_s3 (missing a required argument: 'key'; 3970)
[2024-02-20T10:23:18.348+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-20T10:23:18.382+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
