[2024-02-21T10:10:30.548+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.model_training manual__2024-02-21T10:10:05.191764+00:00 [queued]>
[2024-02-21T10:10:30.560+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.model_training manual__2024-02-21T10:10:05.191764+00:00 [queued]>
[2024-02-21T10:10:30.562+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T10:10:30.577+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): model_training> on 2024-02-21 10:10:05.191764+00:00
[2024-02-21T10:10:30.587+0000] {standard_task_runner.py:60} INFO - Started process 520 to run task
[2024-02-21T10:10:30.590+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'model_training', 'manual__2024-02-21T10:10:05.191764+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmpe47or2ur']
[2024-02-21T10:10:30.593+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask model_training
[2024-02-21T10:10:30.613+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-21T10:10:30.656+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.model_training manual__2024-02-21T10:10:05.191764+00:00 [running]> on host b14d6cdb7c29
[2024-02-21T10:10:30.736+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='model_training' AIRFLOW_CTX_EXECUTION_DATE='2024-02-21T10:10:05.191764+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-21T10:10:05.191764+00:00'
[2024-02-21T10:10:30.972+0000] {logging_mixin.py:188} INFO - data imported from s3
[2024-02-21T10:10:30.978+0000] {logging_mixin.py:188} WARNING - usage: *** [-h] [--alpha ALPHA] [--l1_ratio L1_RATIO]
[2024-02-21T10:10:30.980+0000] {logging_mixin.py:188} WARNING - ***: error: unrecognized arguments: scheduler
[2024-02-21T10:10:31.006+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 2
[2024-02-21T10:10:31.038+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
