[2024-02-21T10:21:36.232+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-21T10:21:17.772910+00:00 [queued]>
[2024-02-21T10:21:36.245+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-21T10:21:17.772910+00:00 [queued]>
[2024-02-21T10:21:36.246+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T10:21:36.265+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-02-21 10:21:17.772910+00:00
[2024-02-21T10:21:36.275+0000] {standard_task_runner.py:60} INFO - Started process 1583 to run task
[2024-02-21T10:21:36.278+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-s3-mlflow', 'upload_to_s3', 'manual__2024-02-21T10:21:17.772910+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/***-aws-mlflow.py', '--cfg-path', '/tmp/tmpe4_f90u0']
[2024-02-21T10:21:36.281+0000] {standard_task_runner.py:88} INFO - Job 68: Subtask upload_to_s3
[2024-02-21T10:21:36.301+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-02-21T10:21:36.360+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-s3-mlflow.upload_to_s3 manual__2024-02-21T10:21:17.772910+00:00 [running]> on host b14d6cdb7c29
[2024-02-21T10:21:36.446+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-s3-mlflow' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-21T10:21:17.772910+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-21T10:21:17.772910+00:00'
[2024-02-21T10:21:36.822+0000] {base_aws.py:581} WARNING - Unable to find AWS Connection ID 's3_conn', switching to empty.
[2024-02-21T10:21:36.823+0000] {base_aws.py:161} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2024-02-21T10:21:37.312+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-02-21T10:21:38.817+0000] {logging_mixin.py:188} INFO - datafile uploaded successfully
[2024-02-21T10:21:38.821+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T10:21:38.836+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=***-s3-mlflow, task_id=upload_to_s3, execution_date=20240221T102117, start_date=20240221T102136, end_date=20240221T102138
[2024-02-21T10:21:38.910+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T10:21:38.950+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
